import "./style.css";
import { Engine } from "./game/engine";
import { Sleeper } from "./game/sleeper";
import {
  ABOUT,
  CERTIFICATIONS,
  CONTACT_NOTE,
  CREDLY_PROFILE,
  EXPERIENCE,
  LIGHTS_HINT,
  PROFILE,
  PROJECTS,
  SKILLS,
} from "./content";

// ------------------------------------------------------------
// Tiny DOM helper: el("p", { class: "x" }, "text", childNode…)
// ------------------------------------------------------------
type Child = Node | string;

function el<K extends keyof HTMLElementTagNameMap>(
  tag: K,
  attrs: Record<string, string> = {},
  ...children: Child[]
): HTMLElementTagNameMap[K] {
  const node = document.createElement(tag);
  for (const [k, v] of Object.entries(attrs)) node.setAttribute(k, v);
  for (const c of children) node.append(c);
  return node;
}

// Every i in his name is a bulb. Wrapping each one gives the stylesheet a
// glass to put a filament behind, and gives the switch beside them something
// to feed — in the cave they are, quite literally, the lights that are off.
function bulbName(name: string): Child[] {
  return [...name].map((ch) =>
    ch.toLowerCase() === "i" ? el("span", { class: "bulb" }, ch) : ch,
  );
}

function chips(items: string[]): HTMLElement {
  return el(
    "div",
    { class: "chips" },
    ...items.map((i) => el("span", { class: "chip" }, i)),
  );
}

function sectionLabel(num: string, title: string): HTMLElement {
  return el(
    "div",
    { class: "section-label" },
    el("span", { class: "num" }, num),
    el("h2", {}, title),
  );
}

// ------------------------------------------------------------
// Page assembly — every direct child of #app gets a floor
// beneath it, generated by the engine after this renders.
// ------------------------------------------------------------
const app = document.getElementById("app")!;

// The switch that feeds the bulbs in his name. It lives here in the page,
// not pinned to a corner, because in the cave it has to be somewhere the
// explorer can physically reach — and the only sensible place for the switch
// is next to the lights it works.
// It carries no printed label: a plate on a wall doesn't have one, the note
// taped under it already says what it does, and a third piece of text in the
// same corner was the thing making that corner look busy. The name a screen
// reader announces lives in aria-label instead, where it also stays correct
// when the lights change.
const lightSwitch = el(
  "button",
  { id: "lights-toggle", class: "switch", type: "button" },
  el("span", { class: "plate", "aria-hidden": "true" }, el("span", { class: "lever" })),
);

// Hero
app.append(
  el(
    "header",
    { class: "hero reveal" },
    el(
      "div",
      { class: "name-row" },
      el("h1", {}, ...bulbName(PROFILE.name)),
      // The switch and the note taped under it travel together, so the note
      // stays stuck to the switch at every width instead of drifting off to
      // wherever the line happens to wrap.
      el(
        "div",
        { class: "switch-stack" },
        lightSwitch,
        el("p", { class: "lights-hint" }, LIGHTS_HINT),
      ),
    ),
    el("p", { class: "role" }, PROFILE.role),
    el("p", { class: "tagline" }, PROFILE.tagline),
    el("p", { class: "meta" }, PROFILE.location),
    el(
      "nav",
      { class: "link-row" },
      ...PROFILE.links.map((l) =>
        el("a", { href: l.url, target: "_blank", rel: "noreferrer" }, l.label),
      ),
    ),
  ),
);

// Projects
app.append(
  el(
    "section",
    { id: "projects", class: "reveal" },
    sectionLabel("01", "Projects"),
    el(
      "div",
      { class: "project-list" },
      ...PROJECTS.map((p) => {
        const inner: Child[] = [
          el("h3", {}, p.title),
          el("p", {}, p.description),
          chips(p.tags),
        ];
        // The whole card is the link, so this is a span, not a nested <a>:
        // it names the destination without being a second click target.
        if (p.link && p.linkLabel) {
          inner.push(el("span", { class: "visit" }, `${p.linkLabel} →`));
        }
        return p.link
          ? el(
              "a",
              { class: "project", href: p.link, target: "_blank", rel: "noreferrer" },
              ...inner,
            )
          : el("div", { class: "project" }, ...inner);
      }),
    ),
  ),
);

// Skills
app.append(
  el(
    "section",
    { id: "skills", class: "reveal" },
    sectionLabel("02", "Skills"),
    el(
      "div",
      { class: "skill-list" },
      ...SKILLS.map((g) =>
        el(
          "div",
          { class: "skill-group" },
          el("span", { class: "group-label" }, g.label),
          chips(g.items),
        ),
      ),
    ),
  ),
);

// About
app.append(
  el(
    "section",
    { id: "about", class: "reveal" },
    sectionLabel("03", "About"),
    ...ABOUT.map((p) => el("p", {}, p)),
  ),
);

// Experience
app.append(
  el(
    "section",
    { id: "experience", class: "reveal" },
    sectionLabel("04", "Experience"),
    el(
      "div",
      { class: "xp-list" },
      ...EXPERIENCE.map((x) =>
        el(
          "div",
          { class: "xp" },
          el(
            "div",
            { class: "top" },
            el("h3", {}, x.role + " · ", el("span", { class: "org" }, x.org)),
            el("span", { class: "period" }, x.period),
          ),
          el("ul", {}, ...x.points.map((pt) => el("li", {}, pt))),
        ),
      ),
    ),
  ),
);

// Certifications
app.append(
  el(
    "section",
    { id: "certifications", class: "reveal" },
    sectionLabel("05", "Certifications"),
    el(
      "div",
      { class: "cert-list" },
      ...CERTIFICATIONS.map((c) =>
        el(
          "div",
          { class: "cert" },
          el(
            "div",
            { class: "top" },
            el("h3", {}, c.name),
            el("span", { class: "period" }, c.year),
          ),
          el("p", { class: "cert-meta" }, c.issuer),
        ),
      ),
    ),
    el(
      "a",
      {
        class: "cert-verify",
        href: CREDLY_PROFILE,
        target: "_blank",
        rel: "noreferrer",
      },
      "View verified badges on Credly →",
    ),
  ),
);

// Contact. Deliberately NOT a mailto: — that has no page to land on, it just
// asks the visitor's machine to open a mail client, and a machine with none
// configured shrugs (on Windows, a "pick an app" dialog; elsewhere, silence).
// Plenty of people read their mail in a browser tab with nothing registered.
// Copying is the one behaviour that works the same everywhere. It is a button
// rather than a link because it performs an action and goes nowhere — an <a>
// that does not navigate lies to anyone using a screen reader.
const emailCopied = el("span", { class: "copied", role: "status" }, "");
const emailLink = el(
  "button",
  {
    class: "email",
    type: "button",
    "aria-label": `Copy email address ${PROFILE.email}`,
    title: "Click to copy",
  },
  PROFILE.email,
);

function sayCopied(message: string): void {
  emailCopied.textContent = message;
  emailCopied.classList.add("show");
  window.setTimeout(() => emailCopied.classList.remove("show"), 2400);
}

emailLink.addEventListener("click", () => {
  navigator.clipboard
    ?.writeText(PROFILE.email)
    .then(() => sayCopied("Copied to your clipboard"))
    // Clipboard access can be refused; the address is on screen regardless,
    // so say what happened rather than failing silently.
    .catch(() => sayCopied("Press Ctrl+C to copy — the address is above"));
});

app.append(
  el(
    "section",
    { id: "contact", class: "contact reveal" },
    sectionLabel("06", "Contact"),
    el("p", {}, CONTACT_NOTE),
    emailLink,
    emailCopied,
  ),
);

// Footer — the cave floor. The last solid platform sits under this.
// The desk canvas only exists in lights-on mode (CSS hides it in the
// cave, where the explorer is awake and busy being the cursor).
const deskCanvas = el("canvas", { class: "desk", "aria-hidden": "true" });
// Size the box from the shared scene geometry rather than repeating the
// numbers in CSS — the whole point is that it matches the cave exactly.
deskCanvas.style.setProperty("--desk-w", String(Sleeper.WIDTH));
deskCanvas.style.setProperty("--desk-h", String(Sleeper.HEIGHT));

// The desk goes below the copyright line: in the cave, the floor he wakes
// on is this canvas's own floor line, and the text has to sit above it.
app.append(
  el(
    "footer",
    { class: "reveal" },
    el("span", {}, `© ${new Date().getFullYear()} ${PROFILE.name}`),
    deskCanvas,
  ),
);

// ------------------------------------------------------------
// Torch mode: the character is the cursor, the torch the light.
// ------------------------------------------------------------
const hint = document.getElementById("hint")!;
const toggle = lightSwitch;

const isTouch = "ontouchstart" in window || navigator.maxTouchPoints > 0;
if (isTouch) {
  document.body.classList.add("touch");
  // No Esc key on a phone — the ☀ button is the lifeline there instead.
  hint.textContent = "◀ ▶ walk · ▲ jump · ▼ descend · ☀ lights";
}

const engine = new Engine(
  () => {
    hint.style.opacity = "0";
  },
  // His torch knocked the switch by his name: that is the way out of the cave.
  () => lightUp(),
);
const sleeper = new Sleeper(deskCanvas);

// Visitors land on the plain scrolling page; "Lights off" opts into the
// cave. On unless this visitor has explicitly turned the lights off before.
const LIGHTS_KEY = "lights-on";
let lightsOn = localStorage.getItem(LIGHTS_KEY) !== "0";

function applyLights(): void {
  // Both modes share the same layout, so the camera position and the scroll
  // position mean the same thing — hand one to the other and the toggle
  // keeps the visitor exactly where they were looking.
  const cameraWas = engine.cameraY;
  const scrollWas = window.scrollY;

  document.body.classList.toggle("lights-on", lightsOn);
  // The switch shows its state by the way the rocker sits; this is that same
  // state said out loud, and the tooltip for anyone unsure what the plate is.
  const label = lightsOn ? "Lights off" : "Lights on";
  toggle.setAttribute("aria-label", label);
  toggle.setAttribute("title", label);
  toggle.setAttribute("aria-pressed", lightsOn ? "false" : "true");

  if (lightsOn) {
    // The view doesn't move — it's already showing this spot — so the
    // animation is the darkness lifting off it. Keep the light canvas on
    // screen for that until the lift finishes.
    document.body.classList.add("lights-rising");
    window.scrollTo({ top: cameraWas, behavior: "instant" });
    sleeper.setEnabled(true);
    engine.beginExit(() => document.body.classList.remove("lights-rising"));
  } else {
    document.body.classList.remove("lights-rising");
    sleeper.setEnabled(false);
    engine.setEnabled(true, scrollWas);
  }
}

function lightUp(): void {
  if (lightsOn) return;
  lightsOn = true;
  localStorage.setItem(LIGHTS_KEY, "1");
  applyLights();
}

toggle.addEventListener("click", () => {
  // One-way. In the cave the switch stops being a control and becomes a thing
  // on a wall: the only way to throw it is to get up there and hit it. CSS
  // takes the pointer off it too, but the guard is what actually decides.
  if (!lightsOn) return;
  lightsOn = false;
  localStorage.setItem(LIGHTS_KEY, "0");
  applyLights();
  toggle.blur();
});

// The lifeline. Reaching the switch is the way back and the launcher makes it
// a short trip, but nobody should be stuck in a 95% dark room because they
// came to read a CV and not to platform for it.
window.addEventListener("keydown", (e) => {
  if (e.key === "Escape") lightUp();
});
// The same lifeline for anyone without a keyboard.
document.getElementById("btn-lights")?.addEventListener("click", () => lightUp());

applyLights();

// ------------------------------------------------------------
// Reveal-on-scroll, lit page only — the CSS gates it, so the cave
// is untouched. Down there the darkness canvas already decides
// what can be seen and the text stays at full strength behind it.
// The observer keeps running in both modes so the state is already
// right the moment the lights come back on.
// ------------------------------------------------------------
// Sections re-arm once they are fully off screen, so the reveal plays
// again on the way back up. The two thresholds give it hysteresis: it
// shows at 15% in and only resets at 0%, never flickering at the edge.
const revealObserver = new IntersectionObserver(
  (entries) => {
    for (const entry of entries) {
      const el = entry.target as HTMLElement;

      if (entry.intersectionRatio >= 0.15) {
        el.classList.add("is-visible");
      } else if (entry.intersectionRatio === 0) {
        // Re-arm pointing at the edge it just left by, so the next pass
        // slides in from the direction the visitor is coming from.
        const leftAbove =
          entry.boundingClientRect.bottom <= (entry.rootBounds?.top ?? 0);
        el.style.setProperty("--reveal-dir", leftAbove ? "-1" : "1");
        el.classList.remove("is-visible");
      }
    }
  },
  { threshold: [0, 0.15], rootMargin: "0px 0px -10% 0px" },
);
document.querySelectorAll(".reveal").forEach((el) => revealObserver.observe(el));
